### ISSUE TITLE
Linter based on rehype

### ISSUE THREAD

**Issue by denysdovhan** [rehypejs/ideas#1]
`remark-lint` is awesome! Let's make the same thing for rehype!

**Comment by wooorm** [comment]
Yes, that would be super! I started work on it a while ago, but was never able to finish it, as HTML has so many things to check for! 😬

**Comment by denysdovhan** [comment]
@wooorm maybe there's a reason to start with reimplementing rules from existing linters, like htmlhint?

**Comment by wooorm** [comment]
Definitely! I invited you to my private, not-really-working, initial work, maybe you’re into setting something up? I also have some newer code, with just some aria rules, that may be easier to convert to something, but it’s only on my computer 😬

Oh, and for inspiration:

* https://github.com/htmllint/htmllint/wiki/Options
* https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md
* https://github.com/DuaneOBrien/A11YLint-Brackets
* https://github.com/sonarwhal/sonarwhal

**Comment by denysdovhan** [comment]
I'll try to take a look at it!

**Comment by ChristianMurphy** [comment]
On a related note, I created selective lint using a similar tech stack, rehype-parse, unified lint rule and unified message control.
The rule API is mainly focused on using CSS selectors as rules.

But the marker message control code could be used for a more generic linter. https://github.com/ChristianMurphy/selective/blob/master/%40selective/marker/marker.js
https://github.com/ChristianMurphy/selective/blob/master/%40selective/rehype/rehype.js

**Comment by wooorm** [comment]
Not yet released but here’s a little bit! https://github.com/rehypejs/rehype/tree/master/packages/rehype-parse#optionsemitparseerrors

**Comment by ChristianMurphy** [comment]
Thanks for starting the discussion @denysdovhan!
We're in the process unifying ideas in with discussions unifiedjs/collective#44
If you'd like to continue this thread, or start a new one https://github.com/rehypejs/rehype/discussions/categories/ideas will be the home for ideas going forward.
