### ISSUE TITLE
Rehype DOM based implementation for browsers

### ISSUE THREAD

**Issue by ChristianMurphy** [rehypejs/ideas#2]
Based on a discussion with @wooorm and @kmck in gitter https://gitter.im/unifiedjs/Lobby?at=5b0db4fce26c847ac89f59bb

In a browser context parse5 add significant weight to bundled JavaScript.
Parse5 mostly functions as a replacement for the DOM model, but in a browser DOM will exist, and parse5 could be dropped.
Allowing direct conversion of DOM to HAST.

**Comment by ChristianMurphy** [comment]
:notebook: It may be possible to optimize the stringify implementation leveraging DOM as well.

**Comment by wooorm** [comment]
@ChristianMurphy what makes you say the last comment?

And thanks for posting!

**Comment by ChristianMurphy** [comment]
Entity escaping adds weight, https://github.com/wooorm/character-entities/blob/master/index.json is awesome, but by itself it can add about 35kb to the bundle size.
We may be able to leverage some of the built in escaping features in browsers.

**Comment by kmck** [comment]
i put together this utility for the parsing side of things based on the implementation of [hast-util-from-parse5](https://github.com/syntax-tree/hast-util-from-parse5):

https://github.com/kmck/hast-util-from-dom/tree/master

i took the fixtures (minus the `data` and `position`) directly from the parse5 util, and the behavior is equivalent in jsdom. i have a feeling it might need some cross-browser attention, but it's a start!

**Comment by kmck** [comment]
more-or-less drop-in replacement for `rehype-parse`:

https://github.com/kmck/rehype-dom-parse

**Comment by wooorm** [comment]
@kmck Feel free to add `rehype-dom-parse` to the list of plugins of [rehype](https://github.com/rehypejs/rehype/blob/master/doc/plugins.md#list-of-plugins)!

And if you’d like you can transform hast-util-from-dom to syntax-tree!
