### ISSUE TITLE
KaTeX preprocessing

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [rehypejs/ideas#3]
There is an [API available for KaTeX](https://khan.github.io/KaTeX/docs/api.html#server-side-rendering-or-rendering-to-a-string).

**Comment by wooorm** [comment]
What's the question? 🤔 what should be done here?

**Comment by make-github-pseudonymous-again** [comment]
Would it be the scope of this project to have a plugin that transforms LaTeX math snippets (embedded into a html document) to html tags? If so, KaTeX could be used to do the transform.

**Comment by wooorm** [comment]
Sure bur that sounds close to this one: 
https://github.com/rokt33r/remark-math/tree/master/packages/rehype-katex, or do you mean something different?

**Comment by make-github-pseudonymous-again** [comment]
Nice! Could not find it by myself. Is there a page that shows *unofficial* rehype/remark plugins?

**Comment by wooorm** [comment]
Here is a list I maintain and that others contribute to: 
https://github.com/rehypejs/rehype/blob/master/doc/plugins.md
Out can also search for rehype and rehype-plugin on npm and github!
