### ISSUE TITLE
rehype-codemirror

### ISSUE THREAD

**Issue by Rokt33r** [rehypejs/ideas#5]
CodeMirror is a code editor. But it is also providing runmode which just does syntax highlighting like highlight.js.

I've already roughly tried in here.

https://github.com/BoostIO/Boostnote.next/commit/db2e16c4620e0356a2b8160b587694ea67026b35#diff-55439261af156770136159a7b2bd0271R33-R138

**Comment by ChristianMurphy** [comment]
https://github.com/craftzdog/remark-react-codemirror might also be able to provide some inspiration

**Comment by ChristianMurphy** [comment]
Thanks for starting the discussion @Rokt33r !
We're in the process unifying ideas in with discussions unifiedjs/collective#44
If you'd like to continue this thread, or start a new one https://github.com/rehypejs/rehype/discussions/categories/ideas will be the home for ideas going forward.
