### ISSUE TITLE
Generic asset inliner (css, js, img)

### ISSUE THREAD

**Issue by marko-knoebl** [rehypejs/ideas#6]
I've created a small generic asset inliner that I'm using for one of my projects:

https://github.com/marko-knoebl/rehype-inline

It's currently installable as npm package `@karuga/rehype-inline` - I'm planning to drop the username prefix.

It inlines css, js and img elements. In contrast to the existing rehype-inline-svg its main goal is creating a single HTML file and not so much optimizing for speed.

I guess this could be included in the list of plugins in the rehype documentation. Before that I'm happy about feedback / testing / suggestions.

**Comment by wooorm** [comment]
Good and idea, and looks nice! Feel free to add it to the list of plugins indeed!

One thing I’d do is to drop the `readFileSync`s and instead pool to files to be read. You can collect a list of pairs of `[node, parent]` (`visit` receives a `parent` as well), and then when the file is asynchronously read, replace `node` in `parent.children`.

The above is most important probably for performance, but maybe an idea: what if there was a limit to file sizes? That if something is bigger than 50kb, it remains external? Not sure if that’s a good idea though, just a hunch.
